app:
    resource: '@AppBundle/Controller/'
    type: annotation

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

login_check:
    path: '/login-check'

logout:
    path: '/logout'