security:
    providers:
        p_1:
            entity:
                class: AppBundle\Entity\Authentication\User
                property: email

    firewalls:
        f_1:
            pattern: /
            provider: p_1
            anonymous: true
            form_login:
                login_path: login
                check_path: login_check
                username_parameter: appbundle_authentication_user[email]
                password_parameter: appbundle_authentication_user[password]
                csrf_token_generator: security.csrf.token_manager
                csrf_parameter: appbundle_authentication_user[csrf_token]
                csrf_token_id: login_form
            logout:
                path: logout
                target: homepage
            remember_me:
                secret: '%secret%'
                lifetime: 604800
                path: /

    encoders:
        AppBundle\Entity\Authentication\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]